import CoreGraphics
import Foundation

/// Extracts tap-mappable geometry from a Verovio-rendered SVG.
///
/// Verovio draws the staff by professional engraving rules, so we cannot reuse
/// our homemade `computeNotePositions` coordinates for hit-testing — the two
/// would diverge. Instead we read the positions straight out of what Verovio
/// actually drew: each `<g class="note" id="...">` carries our exported
/// `NoteEvent.id`, and its notehead `<use transform="translate(x, y)">` gives the
/// note's centre; each `<g class="staff">` lists its five line y-coordinates.
/// This makes a tap resolve to the exact note/pitch the engine rendered.
///
/// The SVG is machine-generated by Verovio with a stable shape, so regex parsing
/// is deliberate here (not hand-written XML), matching how other Verovio hosts
/// read back element positions.
///
/// Failure modes:
///   - SVG lacks a viewBox / pixel size -> Detect: `parse` returns nil
///       -> Recover: caller keeps the previous geometry, tap falls back to no-op.
///   - A note group has no notehead translate (e.g. a rest mis-tagged)
///       -> Detect: that note is skipped -> Recover: remaining notes still map.
struct VerovioSVGGeometry {
    /// A rendered notehead. `point` and coordinates are in viewBox units.
    struct Note {
        let id: String
        let point: CGPoint
    }

    /// One staff of one measure: its five line y's (top→bottom) and horizontal span.
    struct Staff {
        let lineYs: [CGFloat]
        let xRange: ClosedRange<CGFloat>

        /// staff-space = distance between adjacent lines (one diatonic step is half of it).
        var staffSpace: CGFloat { lineYs.count >= 2 ? lineYs[1] - lineYs[0] : 0 }
        var top: CGFloat { lineYs.first ?? 0 }
        var bottom: CGFloat { lineYs.last ?? 0 }
    }

    /// One staff *inside one measure*: the drawn staff plus the x-positions of the
    /// noteheads that fall on it. Enough to place a caret after the last note (or at
    /// the staff's left edge when the measure-staff is empty).
    struct MeasureStaff {
        let staff: Staff
        let noteXs: [CGFloat]
        /// x of the leading glyphs (clef / key / time) drawn before the note area.
        /// Their rightmost x anchors beat 1 for an empty measure that carries them.
        let leadingXs: [CGFloat]
    }

    /// One measure as a column of staves in top-to-bottom (model) order. Verovio
    /// numbers measures sequentially across systems, so `measures[i]` is model
    /// measure `i` regardless of where system breaks fall.
    struct Measure {
        let staves: [MeasureStaff]
    }

    /// The `viewBox` in Verovio units (origin + size).
    let viewBox: CGRect
    /// The SVG's intrinsic pixel size (`width`/`height` attributes).
    let pixelSize: CGSize
    let notes: [Note]
    let staves: [Staff]
    let measures: [Measure]

    /// Multiply a viewBox-unit length by this to get on-screen pixels at the SVG's
    /// intrinsic size. Callers that display the SVG scaled must combine with their
    /// own display scale.
    var unitsPerPixel: CGFloat {
        pixelSize.width > 0 ? viewBox.width / pixelSize.width : 1
    }

    // MARK: - Parsing

    static func parse(_ svg: String) -> VerovioSVGGeometry? {
        guard let viewBox = firstViewBox(in: svg),
              let pixelSize = firstPixelSize(in: svg) else { return nil }
        // Verovio wraps all engraved content in `<g class="page-margin"
        // transform="translate(ox, oy)">`, so every `<path>`/`<use>` coordinate is
        // in that group's inner space. Taps, the caret and the selection ring live
        // in the outer viewBox, so we fold the margin translate into every parsed
        // coordinate — otherwise geometry sits `(ox, oy)` off from what's on screen,
        // which breaks tap→pitch, selection and re-pitch, and parks the caret at the
        // left edge. `.zero` when no page-margin is present.
        //
        // We ALSO subtract the viewBox origin (minX, minY): the surface maps a tap
        // as `location / unitToPoint` and draws a note as `coord * unitToPoint`,
        // both measured from the SVG's top-left — which is viewBox (minX, minY), not
        // (0, 0). Verovio currently emits `viewBox="0 0 …"`, so this is a no-op today,
        // but any non-zero origin (option change, future Verovio) would otherwise
        // shift the whole interaction layer. Normalising here keeps geometry in the
        // same top-left-relative space the surface already assumes.
        let margin = pageMarginOffset(in: svg)
        let origin = CGPoint(x: margin.x - viewBox.minX, y: margin.y - viewBox.minY)
        return VerovioSVGGeometry(
            viewBox: viewBox,
            pixelSize: pixelSize,
            notes: (parseNotes(svg) + parseRests(svg)).map { shift($0, by: origin) },
            staves: parseStaves(svg).map { shift($0, by: origin) },
            measures: parseMeasures(svg).map { shift($0, by: origin) }
        )
    }

    /// The `<g class="page-margin">` translate, or `.zero` if absent. Verovio always
    /// emits one (default 500, 500), but treating a missing one as no offset keeps
    /// the parser robust to option changes.
    private static func pageMarginOffset(in svg: String) -> CGPoint {
        guard let m = firstMatch(#"class="page-margin"\s+transform="translate\(([\d.\-]+),\s*([\d.\-]+)\)""#, in: svg),
              m.count == 3, let x = Double(m[1]), let y = Double(m[2]) else { return .zero }
        return CGPoint(x: x, y: y)
    }

    private static func shift(_ n: Note, by o: CGPoint) -> Note {
        o == .zero ? n : Note(id: n.id, point: CGPoint(x: n.point.x + o.x, y: n.point.y + o.y))
    }

    private static func shift(_ s: Staff, by o: CGPoint) -> Staff {
        o == .zero ? s : Staff(lineYs: s.lineYs.map { $0 + o.y },
                               xRange: (s.xRange.lowerBound + o.x)...(s.xRange.upperBound + o.x))
    }

    private static func shift(_ m: Measure, by o: CGPoint) -> Measure {
        o == .zero ? m : Measure(staves: m.staves.map {
            MeasureStaff(staff: shift($0.staff, by: o),
                         noteXs: $0.noteXs.map { $0 + o.x },
                         leadingXs: $0.leadingXs.map { $0 + o.x })
        })
    }

    private static func firstViewBox(in svg: String) -> CGRect? {
        guard let m = firstMatch(#"viewBox="([\d.\-]+) ([\d.\-]+) ([\d.\-]+) ([\d.\-]+)""#, in: svg),
              m.count == 5,
              let x = Double(m[1]), let y = Double(m[2]),
              let w = Double(m[3]), let h = Double(m[4]) else { return nil }
        return CGRect(x: x, y: y, width: w, height: h)
    }

    private static func firstPixelSize(in svg: String) -> CGSize? {
        guard let m = firstMatch(#"<svg width="([\d.]+)px" height="([\d.]+)px""#, in: svg),
              m.count == 3, let w = Double(m[1]), let h = Double(m[2]) else { return nil }
        return CGSize(width: w, height: h)
    }

    private static func parseNotes(_ svg: String) -> [Note] {
        let ns = svg as NSString
        let noteRe = try! NSRegularExpression(pattern: #"<g id="([A-Za-z][\w\-]*)" class="note">"#)
        let translateRe = try! NSRegularExpression(
            pattern: #"class="notehead">\s*<use[^>]*translate\(([\d.\-]+),\s*([\d.\-]+)\)"#
        )
        var result: [Note] = []
        let full = NSRange(location: 0, length: ns.length)
        for m in noteRe.matches(in: svg, range: full) {
            let id = ns.substring(with: m.range(at: 1))
            // Search a bounded window after the note tag for its notehead translate.
            let start = m.range.location + m.range.length
            let window = NSRange(location: start, length: min(400, ns.length - start))
            guard let t = translateRe.firstMatch(in: svg, range: window),
                  let x = Double(ns.substring(with: t.range(at: 1))),
                  let y = Double(ns.substring(with: t.range(at: 2))) else { continue }
            result.append(Note(id: id, point: CGPoint(x: x, y: y)))
        }
        return result
    }

    /// Rests carry the same exported `NoteEvent.id` as notes (`MusicXMLExporter`
    /// tags `<note><rest/>` too), so a tap on a rest can select it. Verovio draws a
    /// rest as `<g id="..." class="rest">` with the glyph `<use transform="translate(
    /// x, y)">` — no `notehead` wrapper, so it needs its own scan. Returned merged
    /// into `notes` so hit-testing and selection treat rests exactly like noteheads.
    private static func parseRests(_ svg: String) -> [Note] {
        let ns = svg as NSString
        // Verovio draws a normal rest as class="rest" but an empty measure as a
        // centered full-measure rest class="mRest" — match both so a tap on an
        // empty measure's rest still finds a target (MuseScore mRest is selectable).
        let restRe = try! NSRegularExpression(pattern: #"<g id="([A-Za-z][\w\-]*)" class="(?:rest|mRest)">"#)
        let translateRe = try! NSRegularExpression(
            pattern: #"<use[^>]*translate\(([\d.\-]+),\s*([\d.\-]+)\)"#
        )
        var result: [Note] = []
        let full = NSRange(location: 0, length: ns.length)
        for m in restRe.matches(in: svg, range: full) {
            let id = ns.substring(with: m.range(at: 1))
            let start = m.range.location + m.range.length
            let window = NSRange(location: start, length: min(400, ns.length - start))
            guard let t = translateRe.firstMatch(in: svg, range: window),
                  let x = Double(ns.substring(with: t.range(at: 1))),
                  let y = Double(ns.substring(with: t.range(at: 2))) else { continue }
            result.append(Note(id: id, point: CGPoint(x: x, y: y)))
        }
        return result
    }

    private static func parseStaves(_ svg: String) -> [Staff] {
        let ns = svg as NSString
        let staffRe = try! NSRegularExpression(pattern: #"<g id="[\w\-]+" class="staff">"#)
        let lineRe = try! NSRegularExpression(pattern: #"<path d="M([\d.\-]+) ([\d.\-]+) L([\d.\-]+) ([\d.\-]+)""#)
        var result: [Staff] = []
        let full = NSRange(location: 0, length: ns.length)
        for m in staffRe.matches(in: svg, range: full) {
            let start = m.range.location + m.range.length
            let window = NSRange(location: start, length: min(700, ns.length - start))
            let lines = lineRe.matches(in: svg, range: window).prefix(5)
            guard lines.count == 5 else { continue }
            var ys: [CGFloat] = []
            var minX = CGFloat.greatestFiniteMagnitude
            var maxX = -CGFloat.greatestFiniteMagnitude
            for l in lines {
                guard let x1 = Double(ns.substring(with: l.range(at: 1))),
                      let y1 = Double(ns.substring(with: l.range(at: 2))),
                      let x2 = Double(ns.substring(with: l.range(at: 3))) else { continue }
                ys.append(CGFloat(y1))
                minX = min(minX, CGFloat(x1)); maxX = max(maxX, CGFloat(x2))
            }
            guard ys.count == 5, minX <= maxX else { continue }
            result.append(Staff(lineYs: ys, xRange: minX...maxX))
        }
        return result
    }

    /// Group staves and noteheads by their enclosing `<g class="measure">`, in
    /// document order. Within a measure the staves come in model order, and each
    /// notehead is attributed to the staff whose source range encloses it. This is
    /// what lets a caret land in the exact (measure, staff) the model cursor names.
    private static func parseMeasures(_ svg: String) -> [Measure] {
        let ns = svg as NSString
        let measureRe = try! NSRegularExpression(pattern: #"<g id="[\w\-]+" class="measure">"#)
        let staffRe = try! NSRegularExpression(pattern: #"<g id="[\w\-]+" class="staff">"#)
        let lineRe = try! NSRegularExpression(pattern: #"<path d="M([\d.\-]+) ([\d.\-]+) L([\d.\-]+) ([\d.\-]+)""#)
        let translateRe = try! NSRegularExpression(
            pattern: #"class="notehead">\s*<use[^>]*translate\(([\d.\-]+),\s*([\d.\-]+)\)"#
        )
        // Leading glyphs (clef / key / time) sit before the note area; their
        // rightmost x anchors beat 1 in an empty measure that carries them.
        let leadingRe = try! NSRegularExpression(
            pattern: #"class="(?:clef|keySig|meterSig)">\s*<use[^>]*translate\(([\d.\-]+),\s*([\d.\-]+)\)"#
        )
        let full = NSRange(location: 0, length: ns.length)
        let measureStarts = measureRe.matches(in: svg, range: full).map { $0.range.location }
        guard !measureStarts.isEmpty else { return [] }

        var result: [Measure] = []
        for (i, mStart) in measureStarts.enumerated() {
            let mEnd = i + 1 < measureStarts.count ? measureStarts[i + 1] : ns.length
            let mRange = NSRange(location: mStart, length: mEnd - mStart)
            let staffStarts = staffRe.matches(in: svg, range: mRange).map { $0.range.location }
            var measureStaves: [MeasureStaff] = []
            for (j, sStart) in staffStarts.enumerated() {
                let sEnd = j + 1 < staffStarts.count ? staffStarts[j + 1] : mEnd
                let sRange = NSRange(location: sStart, length: sEnd - sStart)
                guard let staff = parseStaff(in: sRange, ns: ns, lineRe: lineRe) else { continue }
                let noteXs = translateRe.matches(in: svg, range: sRange).compactMap {
                    Double(ns.substring(with: $0.range(at: 1))).map { CGFloat($0) }
                }
                let leadingXs = leadingRe.matches(in: svg, range: sRange).compactMap {
                    Double(ns.substring(with: $0.range(at: 1))).map { CGFloat($0) }
                }
                measureStaves.append(MeasureStaff(staff: staff, noteXs: noteXs, leadingXs: leadingXs))
            }
            result.append(Measure(staves: measureStaves))
        }
        return result
    }

    /// Parse a single `<g class="staff">` (its five line y's and x-span) from a
    /// bounded source range. Shared by the flat staff list and measure grouping.
    private static func parseStaff(in range: NSRange, ns: NSString,
                                   lineRe: NSRegularExpression) -> Staff? {
        let lines = lineRe.matches(in: ns as String, range: range).prefix(5)
        guard lines.count == 5 else { return nil }
        var ys: [CGFloat] = []
        var minX = CGFloat.greatestFiniteMagnitude
        var maxX = -CGFloat.greatestFiniteMagnitude
        for l in lines {
            guard let x1 = Double(ns.substring(with: l.range(at: 1))),
                  let y1 = Double(ns.substring(with: l.range(at: 2))),
                  let x2 = Double(ns.substring(with: l.range(at: 3))) else { continue }
            ys.append(CGFloat(y1))
            minX = min(minX, CGFloat(x1)); maxX = max(maxX, CGFloat(x2))
        }
        guard ys.count == 5, minX <= maxX else { return nil }
        return Staff(lineYs: ys, xRange: minX...maxX)
    }

    private static func firstMatch(_ pattern: String, in s: String) -> [String]? {
        let ns = s as NSString
        guard let re = try? NSRegularExpression(pattern: pattern),
              let m = re.firstMatch(in: s, range: NSRange(location: 0, length: ns.length))
        else { return nil }
        return (0..<m.numberOfRanges).map { ns.substring(with: m.range(at: $0)) }
    }

    // MARK: - Tap queries (viewBox units)

    /// The note whose notehead is within `tolerance` (viewBox units) of `point`,
    /// nearest first. Returns the exported `NoteEvent.id` string.
    func note(near point: CGPoint, tolerance: CGFloat) -> String? {
        var best: (id: String, d2: CGFloat)?
        for n in notes {
            let dx = n.point.x - point.x, dy = n.point.y - point.y
            let d2 = dx * dx + dy * dy
            if d2 <= tolerance * tolerance, best == nil || d2 < best!.d2 {
                best = (n.id, d2)
            }
        }
        return best?.id
    }

    /// The staff whose line band is vertically closest to `y` (viewBox units).
    func nearestStaff(toY y: CGFloat) -> Staff? {
        staves.min { a, b in
            distance(y, toBand: a) < distance(y, toBand: b)
        }
    }

    /// Distinct staff bands (unique top-line y), sorted top→bottom. Verovio draws
    /// the same staff once per measure, so the raw `staves` list repeats each band;
    /// this collapses those repeats to one entry per rendered staff row. Systems
    /// stack vertically, so on a multi-line score the bands stay globally ordered
    /// by y (system 1's staves, then system 2's, …).
    var staffBands: [CGFloat] {
        let tol = (staves.first?.staffSpace ?? 100) * 0.5
        var bands: [CGFloat] = []
        for top in staves.map(\.top).sorted() {
            if let last = bands.last, abs(top - last) <= tol { continue }
            bands.append(top)
        }
        return bands
    }

    /// The tapped staff together with its position within its system — 0 is the
    /// topmost model staff (e.g. the treble of a piano grand staff), 1 the next
    /// down, and so on. Assumes every system renders all `staffCount` model staves
    /// in order (Verovio's default), so the band's global rank mod `staffCount`
    /// is the staff's model index. This is what lets a tap on the bass staff read
    /// the bass clef instead of whichever staff happened to be selected.
    func nearestStaffWithPosition(toY y: CGFloat, staffCount: Int) -> (staff: Staff, positionInSystem: Int)? {
        guard staffCount > 0, let staff = nearestStaff(toY: y) else { return nil }
        let tol = max(staff.staffSpace * 0.5, 1)
        guard let rank = staffBands.firstIndex(where: { abs($0 - staff.top) <= tol }) else { return nil }
        return (staff, rank % staffCount)
    }

    /// The caret x for the given (measure, staff-in-measure) together with that
    /// staff. The caret sits a small gap past the last notehead of the measure-staff
    /// (where an appended note lands), or a small indent from the staff's left edge
    /// when the measure-staff is empty. nil if the indices fall outside what was
    /// rendered (e.g. the score re-engraved to fewer measures).
    /// The note-input caret band (viewBox units) at `staffInMeasure` of `measureIndex`.
    /// MuseScore draws the note-input caret not as a hairline but as a translucent
    /// vertical band sitting on the insertion beat, spanning the full system height —
    /// so on a grand staff it crosses both staves. `x` is the band centre (the
    /// insertion point on the active staff), `width` is roughly one beat-cell, and
    /// top/bottom run half a staff-space past the system's outer lines so the band
    /// reads clearly. nil if the measure/staff was not rendered.
    func insertionColumn(measureIndex: Int, staffInMeasure: Int)
        -> (x: CGFloat, top: CGFloat, bottom: CGFloat, width: CGFloat)? {
        guard measureIndex >= 0, measureIndex < measures.count else { return nil }
        let staves = measures[measureIndex].staves
        guard staffInMeasure >= 0, staffInMeasure < staves.count else { return nil }
        let ms = staves[staffInMeasure]
        let ss = max(ms.staff.staffSpace, 1)
        // Where the next note lands (all offsets measured against Verovio's default
        // spacing, verified against rendered noteheads — see PlacementTests):
        //   • notes present → just past the last notehead (append point)
        //   • empty but carrying clef/key/time → beat 1 sits ~3.1 sp past them
        //   • empty interior measure → beat 1 sits 1 sp past the barline
        let x: CGFloat
        if let lastNote = ms.noteXs.max() {
            x = lastNote + ss * 0.75
        } else if let leadRight = ms.leadingXs.max() {
            x = leadRight + ss * 3.1
        } else {
            x = ms.staff.xRange.lowerBound + ss * 1.0
        }
        let allStaves = staves.map(\.staff)
        let overshoot = ms.staff.staffSpace * 0.5
        let top = (allStaves.map { $0.top }.min() ?? ms.staff.top) - overshoot
        let bottom = (allStaves.map { $0.bottom }.max() ?? ms.staff.bottom) + overshoot
        let width = max(ms.staff.staffSpace * 1.1, 1)
        return (x, top, bottom, width)
    }

    /// The playback cursor line for `measureIndex` at horizontal `fraction`
    /// (0…1 across that measure's staff span). Spans vertically from the top of the
    /// measure's highest staff to the bottom of its lowest — the whole system
    /// height, as MuseScore's playback cursor does — so on a grand staff the line
    /// crosses both staves. `width` scales with the staff so the bar reads the same
    /// at any zoom. All values in viewBox units. nil if the measure was not rendered.
    func playheadLine(measureIndex: Int, fraction: CGFloat)
        -> (x: CGFloat, top: CGFloat, bottom: CGFloat, width: CGFloat)? {
        guard measureIndex >= 0, measureIndex < measures.count else { return nil }
        let staves = measures[measureIndex].staves.map(\.staff)
        guard let firstStaff = staves.first else { return nil }
        let lo = staves.map { $0.xRange.lowerBound }.min() ?? firstStaff.xRange.lowerBound
        let hi = staves.map { $0.xRange.upperBound }.max() ?? firstStaff.xRange.upperBound
        let clamped = min(max(fraction, 0), 1)
        let x = lo + (hi - lo) * clamped
        let top = staves.map { $0.top }.min() ?? firstStaff.top
        let bottom = staves.map { $0.bottom }.max() ?? firstStaff.bottom
        let width = max(firstStaff.staffSpace * 0.28, 1)
        return (x, top, bottom, width)
    }

    /// Resolve a tapped point to the (measure, staff-in-measure) it lands in, with
    /// that staff. Horizontal position picks the measure (its staff x-range), vertical
    /// position picks the staff within it (nearest by line-band, within a staff-space
    /// of the tap). This is what lets a tap in the 2nd measure of a wide score add
    /// there — not always in the currently-selected measure. nil for a tap off any
    /// staff (e.g. in a page margin).
    func locate(x: CGFloat, y: CGFloat) -> (measureIndex: Int, staffInMeasure: Int, staff: Staff)? {
        var best: (measureIndex: Int, staffInMeasure: Int, staff: Staff)?
        var bestDist = CGFloat.greatestFiniteMagnitude
        for (mi, measure) in measures.enumerated() {
            for (si, ms) in measure.staves.enumerated() {
                let s = ms.staff
                guard x >= s.xRange.lowerBound, x <= s.xRange.upperBound else { continue }
                let tol = max(s.staffSpace, 1) * 2
                let dist = y < s.top ? s.top - y : (y > s.bottom ? y - s.bottom : 0)
                guard dist <= tol, dist < bestDist else { continue }
                bestDist = dist
                best = (mi, si, s)
            }
        }
        return best
    }

    /// Diatonic steps of `y` above the staff's middle (3rd) line — positive is
    /// upward (screen-up = smaller y), so a note one line higher than the middle
    /// line is +2 steps. One diatonic step is half a staff-space. Combined with a
    /// clef's middle-line pitch this yields the tapped pitch. Returns nil for a
    /// staff without a resolvable middle line.
    func diatonicStepsAboveMiddle(ofStaff staff: Staff, y: CGFloat) -> Int? {
        guard staff.lineYs.count == 5, staff.staffSpace > 0 else { return nil }
        let middleY = staff.lineYs[2]
        let stepHeight = staff.staffSpace / 2
        return Int(((middleY - y) / stepHeight).rounded())
    }

    private func distance(_ y: CGFloat, toBand s: Staff) -> CGFloat {
        if y < s.top { return s.top - y }
        if y > s.bottom { return y - s.bottom }
        return 0
    }
}
