import CoreGraphics
import Foundation

/// Extracts tap-mappable geometry from a Verovio-rendered SVG.
///
/// Verovio draws the staff by professional engraving rules, so we cannot reuse
/// our homemade `computeNotePositions` coordinates for hit-testing — the two
/// would diverge. Instead we read the positions straight out of what Verovio
/// actually drew: each `<g class="note" id="...">` carries our exported
/// `NoteEvent.id`, and its notehead `<use transform="translate(x, y)">` gives the
/// note's centre; each `<g class="staff">` lists its five line y-coordinates.
/// This makes a tap resolve to the exact note/pitch the engine rendered.
///
/// The SVG is machine-generated by Verovio with a stable shape, so regex parsing
/// is deliberate here (not hand-written XML), matching how other Verovio hosts
/// read back element positions.
///
/// Failure modes:
///   - SVG lacks a viewBox / pixel size -> Detect: `parse` returns nil
///       -> Recover: caller keeps the previous geometry, tap falls back to no-op.
///   - A note group has no notehead translate (e.g. a rest mis-tagged)
///       -> Detect: that note is skipped -> Recover: remaining notes still map.
struct VerovioSVGGeometry {
    /// A rendered notehead. `point` and coordinates are in viewBox units.
    struct Note {
        let id: String
        let point: CGPoint
    }

    /// One staff of one measure: its five line y's (top→bottom) and horizontal span.
    struct Staff {
        let lineYs: [CGFloat]
        let xRange: ClosedRange<CGFloat>

        /// staff-space = distance between adjacent lines (one diatonic step is half of it).
        var staffSpace: CGFloat { lineYs.count >= 2 ? lineYs[1] - lineYs[0] : 0 }
        var top: CGFloat { lineYs.first ?? 0 }
        var bottom: CGFloat { lineYs.last ?? 0 }
    }

    /// The `viewBox` in Verovio units (origin + size).
    let viewBox: CGRect
    /// The SVG's intrinsic pixel size (`width`/`height` attributes).
    let pixelSize: CGSize
    let notes: [Note]
    let staves: [Staff]

    /// Multiply a viewBox-unit length by this to get on-screen pixels at the SVG's
    /// intrinsic size. Callers that display the SVG scaled must combine with their
    /// own display scale.
    var unitsPerPixel: CGFloat {
        pixelSize.width > 0 ? viewBox.width / pixelSize.width : 1
    }

    // MARK: - Parsing

    static func parse(_ svg: String) -> VerovioSVGGeometry? {
        guard let viewBox = firstViewBox(in: svg),
              let pixelSize = firstPixelSize(in: svg) else { return nil }
        return VerovioSVGGeometry(
            viewBox: viewBox,
            pixelSize: pixelSize,
            notes: parseNotes(svg),
            staves: parseStaves(svg)
        )
    }

    private static func firstViewBox(in svg: String) -> CGRect? {
        guard let m = firstMatch(#"viewBox="([\d.\-]+) ([\d.\-]+) ([\d.\-]+) ([\d.\-]+)""#, in: svg),
              m.count == 5,
              let x = Double(m[1]), let y = Double(m[2]),
              let w = Double(m[3]), let h = Double(m[4]) else { return nil }
        return CGRect(x: x, y: y, width: w, height: h)
    }

    private static func firstPixelSize(in svg: String) -> CGSize? {
        guard let m = firstMatch(#"<svg width="([\d.]+)px" height="([\d.]+)px""#, in: svg),
              m.count == 3, let w = Double(m[1]), let h = Double(m[2]) else { return nil }
        return CGSize(width: w, height: h)
    }

    private static func parseNotes(_ svg: String) -> [Note] {
        let ns = svg as NSString
        let noteRe = try! NSRegularExpression(pattern: #"<g id="([A-Za-z][\w\-]*)" class="note">"#)
        let translateRe = try! NSRegularExpression(
            pattern: #"class="notehead">\s*<use[^>]*translate\(([\d.\-]+),\s*([\d.\-]+)\)"#
        )
        var result: [Note] = []
        let full = NSRange(location: 0, length: ns.length)
        for m in noteRe.matches(in: svg, range: full) {
            let id = ns.substring(with: m.range(at: 1))
            // Search a bounded window after the note tag for its notehead translate.
            let start = m.range.location + m.range.length
            let window = NSRange(location: start, length: min(400, ns.length - start))
            guard let t = translateRe.firstMatch(in: svg, range: window),
                  let x = Double(ns.substring(with: t.range(at: 1))),
                  let y = Double(ns.substring(with: t.range(at: 2))) else { continue }
            result.append(Note(id: id, point: CGPoint(x: x, y: y)))
        }
        return result
    }

    private static func parseStaves(_ svg: String) -> [Staff] {
        let ns = svg as NSString
        let staffRe = try! NSRegularExpression(pattern: #"<g id="[\w\-]+" class="staff">"#)
        let lineRe = try! NSRegularExpression(pattern: #"<path d="M([\d.\-]+) ([\d.\-]+) L([\d.\-]+) ([\d.\-]+)""#)
        var result: [Staff] = []
        let full = NSRange(location: 0, length: ns.length)
        for m in staffRe.matches(in: svg, range: full) {
            let start = m.range.location + m.range.length
            let window = NSRange(location: start, length: min(700, ns.length - start))
            let lines = lineRe.matches(in: svg, range: window).prefix(5)
            guard lines.count == 5 else { continue }
            var ys: [CGFloat] = []
            var minX = CGFloat.greatestFiniteMagnitude
            var maxX = -CGFloat.greatestFiniteMagnitude
            for l in lines {
                guard let x1 = Double(ns.substring(with: l.range(at: 1))),
                      let y1 = Double(ns.substring(with: l.range(at: 2))),
                      let x2 = Double(ns.substring(with: l.range(at: 3))) else { continue }
                ys.append(CGFloat(y1))
                minX = min(minX, CGFloat(x1)); maxX = max(maxX, CGFloat(x2))
            }
            guard ys.count == 5, minX <= maxX else { continue }
            result.append(Staff(lineYs: ys, xRange: minX...maxX))
        }
        return result
    }

    private static func firstMatch(_ pattern: String, in s: String) -> [String]? {
        let ns = s as NSString
        guard let re = try? NSRegularExpression(pattern: pattern),
              let m = re.firstMatch(in: s, range: NSRange(location: 0, length: ns.length))
        else { return nil }
        return (0..<m.numberOfRanges).map { ns.substring(with: m.range(at: $0)) }
    }

    // MARK: - Tap queries (viewBox units)

    /// The note whose notehead is within `tolerance` (viewBox units) of `point`,
    /// nearest first. Returns the exported `NoteEvent.id` string.
    func note(near point: CGPoint, tolerance: CGFloat) -> String? {
        var best: (id: String, d2: CGFloat)?
        for n in notes {
            let dx = n.point.x - point.x, dy = n.point.y - point.y
            let d2 = dx * dx + dy * dy
            if d2 <= tolerance * tolerance, best == nil || d2 < best!.d2 {
                best = (n.id, d2)
            }
        }
        return best?.id
    }

    /// The staff whose line band is vertically closest to `y` (viewBox units).
    func nearestStaff(toY y: CGFloat) -> Staff? {
        staves.min { a, b in
            distance(y, toBand: a) < distance(y, toBand: b)
        }
    }

    /// Diatonic steps of `y` above the staff's middle (3rd) line — positive is
    /// upward (screen-up = smaller y), so a note one line higher than the middle
    /// line is +2 steps. One diatonic step is half a staff-space. Combined with a
    /// clef's middle-line pitch this yields the tapped pitch. Returns nil for a
    /// staff without a resolvable middle line.
    func diatonicStepsAboveMiddle(ofStaff staff: Staff, y: CGFloat) -> Int? {
        guard staff.lineYs.count == 5, staff.staffSpace > 0 else { return nil }
        let middleY = staff.lineYs[2]
        let stepHeight = staff.staffSpace / 2
        return Int(((middleY - y) / stepHeight).rounded())
    }

    private func distance(_ y: CGFloat, toBand s: Staff) -> CGFloat {
        if y < s.top { return s.top - y }
        if y > s.bottom { return y - s.bottom }
        return 0
    }
}
